apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-podaffinity
  name: nginx-podaffinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-podaffinity
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-podaffinity
    spec:
      containers:
      - image: nginx
        name: nginx-podaffinity
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app 
                operator: In
                values:
                - redis
            topologyKey: kubernetes.io/hostname

