apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-toleration
  name: nginx-toleration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-toleration
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-toleration
    spec:
      tolerations:
      - key: "tenant"
        operator: "Equal"
        value: "marcelo"
        effect: "NoSchedule"
      containers:
      - image: nginx
        name: nginx
