apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-antiaffinity
  name: nginx-antiaffinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-antiaffinity
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-antiaffinity
    spec:
      containers:
      - image: nginx
        name: nginx-antiaffinity
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app 
                operator: In
                values:
                - nginx-antiaffinity
            topologyKey: kubernetes.io/hostname

